// Ҳуҷраи омӯзгор ва ҳамроҳшавии хонанда ба синф: матни интерфейс (tj / ru / en).
export const CLASS_TEXT = {
    tj: {
        // Ҳамроҳшавӣ
        joinTitle: "Ба синф ҳамроҳ шавед",
        codeLabel: "Рамзи синф",
        codePlaceholder: "Масалан: K7M2QX",
        codeFind: "Ёфтан",
        notFound: "Синф бо ин рамз ёфт нашуд. Рамзро аз омӯзгор боз пурсед.",
        full: "Синф пур аст (60 хонанда). Ба омӯзгор гӯед.",
        teacher: "Омӯзгор",
        students: "{{n}} хонанда ҳамроҳ шудааст",
        nameLabel: "Ном ва насаби шумо",
        namePlaceholder: "Масалан: Ҷамшед Раҳимов",
        nameHint: "Почта ва парол лозим нест — омӯзгор шуморо бо ҳамин ном мешиносад.",
        asUser: "Шумо ҳамчун {{name}} ҳамроҳ мешавед.",
        consent: "Омӯзгори шумо натиҷаи тест ва касбҳоеро, ки месанҷед, мебинад. Дигарон намебинанд.",
        join: "Ҳамроҳ шудан",
        joined: "Шумо дар синфи «{{name}}» ҳастед!",
        joinedHint: "Акнун тестро гузаред ва 1–2 касбро санҷед — натиҷа худкор ба омӯзгор меравад.",
        startQuiz: "Тестро оғоз кунед",
        tryCareer: "Худро дар касб санҷед",
        sameDevice: "Тест ва санҷишро дар ҳамин телефон ё компютер гузаред — бе почта сайт шуморо дар ҳамин дастгоҳ мешиносад.",
        leave: "Аз синф баромадан",
        myClasses: "Синфи ман",
        // Омӯзгор: дархост
        teacherRoom: "Ҳуҷраи омӯзгор",
        teacherIntro: "Синфи худро созед, рамзро ба хонандагон диҳед ва бинед, ки кадом самтро гирифтанд, кадом касбҳоро санҷиданд ва боварии онҳо чӣ тавр тағйир ёфт.",
        requestTitle: "Шумо омӯзгор ҳастед?",
        studentCardText: "Агар омӯзгор ба шумо рамзи синф дода бошад, ҳамроҳ шавед — натиҷаи тест ва касбҳое, ки месанҷед, ба омӯзгоратон намоён мешаванд ва ӯ ба шумо дар интихоб кӯмак мекунад.",
        studentCardButton: "Рамзро ворид кунед",
        teacherCardText: "Агар нақши омӯзгор дошта бошед, мебинед, ки хонандагонатон чӣ тавр касб интихоб карда истодаанд: кадом самтро гирифтанд, кадом касбҳоро санҷиданд ва боварии онҳо чӣ тавр тағйир ёфт.",
        teacherCardButton: "Нақши омӯзгорро гиред",
        requestText: "Дархост фиристед — баъди тасдиқ «Ҳуҷраи омӯзгор» кушода мешавад.",
        school: "Мактаб",
        schoolPlaceholder: "Масалан: Мактаби №5, ш. Хуҷанд",
        subject: "Фан (ихтиёрӣ)",
        city: "Шаҳр ё ноҳия",
        phone: "Телефон (ихтиёрӣ)",
        send: "Фиристодан",
        pending: "Дархости шумо фиристода шуд ва интизори тасдиқ аст. Одатан то 1 рӯз.",
        rejected: "Дархост тасдиқ нашуд. Агар хато бошад, маълумотро аниқтар нависед ва боз фиристед.",
        // Омӯзгор: синфҳо
        newClass: "Синф созед",
        className: "Номи синф",
        classNamePlaceholder: "Масалан: 11 «А»",
        grade: "Синф",
        gradeLabel: "синфи {{n}}",
        create: "Сохтан",
        noClasses: "Ҳанӯз синф нест. Аввалинашро созед — 1 дақиқа.",
        joinedCount: "ҳамроҳ шуданд",
        quizCount: "тест гузаштанд",
        trialCount: "касб санҷиданд",
        archived: "Бойгонӣ",
        open: "Кушодан",
        // Омӯзгор: саҳифаи синф
        back: "Ҳамаи синфҳо",
        share: "Ба хонандагон фиристед",
        link: "Пайванд",
        copy: "Нусха",
        copied: "Нусха шуд",
        qr: "QR-код барои тахта ё проектор",
        telegram: "Матн барои Telegram",
        telegramText: "Салом! Барои интихоби касб тести «Ихтисоси ман»-ро гузаред ва 1–2 касбро санҷед (10–15 дақиқа): {{link}} — рамзи синф: {{code}}",
        sendTelegram: "Ба Telegram",
        reminderText: "Салом! Шумо ҳанӯз тест ва санҷиши касбро нагузаштаед. Лутфан то охири ҳафта гузаред: {{link}}",
        copyReminder: "Матни ёдраскунӣ",
        refresh: "Нав кардан",
        csv: "Excel (CSV)",
        print: "Чоп / PDF",
        hideNames: "Номҳоро пинҳон кунед",
        showNames: "Номҳоро нишон диҳед",
        progress: "Пешрафт",
        directions: "Самтҳои синф",
        confidence: "Боварӣ ба интихоб",
        before: "пеш",
        after: "баъд",
        notFit: "{{n}} бор хонанда фаҳмид, ки касб ба ӯ мувофиқ нест",
        all: "Ҳама",
        noQuiz: "Тест нагузаштаанд",
        noTrial: "Касб насанҷидаанд",
        student: "Хонанда",
        quiz: "Тест",
        direction: "Самт",
        careersTried: "Касбҳо",
        lastActive: "Охирин",
        noStudents: "Ҳанӯз касе ҳамроҳ нашудааст. Пайванд ё QR-ро ба хонандагон диҳед.",
        empty: "Дар ин филтр касе нест.",
        topCareers: "Ихтисосҳои мувофиқ аз тест",
        tried: "Касбҳои санҷидашуда",
        solved: "ҳал: {{n}}/{{t}}",
        liked: "писанд: {{n}}/{{t}}",
        fit: "Мувофиқ",
        notFitShort: "Мувофиқ нест",
        plan: "Нақшаи ҳуҷҷатсупорӣ: {{n}} интихоб",
        remove: "Аз синф хориҷ кардан",
        removeConfirm: "{{name}}-ро аз синф хориҷ кунем? Натиҷаҳои ӯ нест намешаванд.",
        archive: "Ба бойгонӣ",
        unarchive: "Аз бойгонӣ",
        guest: "бе почта",
        notFoundClass: "Синф ёфт нашуд.",
        error: "Нашуд. Боз кӯшиш кунед.",
        demoNote: "Номҳо пинҳон — барои намоиш дар экран.",
    },
    ru: {
        joinTitle: "Присоединитесь к классу",
        codeLabel: "Код класса",
        codePlaceholder: "Например: K7M2QX",
        codeFind: "Найти",
        notFound: "Класс с таким кодом не найден. Уточните код у учителя.",
        full: "Класс заполнен (60 учеников). Скажите учителю.",
        teacher: "Учитель",
        students: "Присоединилось учеников: {{n}}",
        nameLabel: "Ваши имя и фамилия",
        namePlaceholder: "Например: Джамшед Рахимов",
        nameHint: "Почта и пароль не нужны — учитель узнает вас по этому имени.",
        asUser: "Вы присоединяетесь как {{name}}.",
        consent: "Ваш учитель увидит результат теста и профессии, которые вы попробуете. Другие не увидят.",
        join: "Присоединиться",
        joined: "Вы в классе «{{name}}»!",
        joinedHint: "Теперь пройдите тест и попробуйте 1–2 профессии — результат автоматически попадёт к учителю.",
        startQuiz: "Начать тест",
        tryCareer: "Попробуйте себя в профессии",
        sameDevice: "Проходите тест и пробу на этом же телефоне или компьютере — без почты сайт узнаёт вас только на этом устройстве.",
        leave: "Выйти из класса",
        myClasses: "Мой класс",
        teacherRoom: "Кабинет учителя",
        teacherIntro: "Создайте свой класс, дайте ученикам код и смотрите, какое направление они получили, какие профессии попробовали и как изменилась их уверенность.",
        requestTitle: "Вы учитель?",
        studentCardText: "Если учитель дал вам код класса, присоединитесь — результат теста и профессии, которые вы попробуете, увидит ваш учитель и поможет с выбором.",
        studentCardButton: "Ввести код",
        teacherCardText: "С ролью учителя вы видите, как ваши ученики выбирают профессию: какое направление получили, какие профессии попробовали и как изменилась их уверенность.",
        teacherCardButton: "Получить роль учителя",
        requestText: "Отправьте заявку — после подтверждения откроется «Кабинет учителя».",
        school: "Школа",
        schoolPlaceholder: "Например: Школа №5, г. Худжанд",
        subject: "Предмет (необязательно)",
        city: "Город или район",
        phone: "Телефон (необязательно)",
        send: "Отправить",
        pending: "Заявка отправлена и ждёт подтверждения. Обычно до 1 дня.",
        rejected: "Заявка не подтверждена. Если это ошибка, уточните данные и отправьте снова.",
        newClass: "Создать класс",
        className: "Название класса",
        classNamePlaceholder: "Например: 11 «А»",
        grade: "Класс",
        gradeLabel: "{{n}} класс",
        create: "Создать",
        noClasses: "Классов пока нет. Создайте первый — это 1 минута.",
        joinedCount: "присоединились",
        quizCount: "прошли тест",
        trialCount: "попробовали профессию",
        archived: "Архив",
        open: "Открыть",
        back: "Все классы",
        share: "Отправьте ученикам",
        link: "Ссылка",
        copy: "Копировать",
        copied: "Скопировано",
        qr: "QR-код для доски или проектора",
        telegram: "Текст для Telegram",
        telegramText: "Здравствуйте! Для выбора профессии пройдите тест «Ихтисоси ман» и попробуйте 1–2 профессии (10–15 минут): {{link}} — код класса: {{code}}",
        sendTelegram: "В Telegram",
        reminderText: "Здравствуйте! Вы ещё не прошли тест и пробу профессии. Пожалуйста, пройдите до конца недели: {{link}}",
        copyReminder: "Текст напоминания",
        refresh: "Обновить",
        csv: "Excel (CSV)",
        print: "Печать / PDF",
        hideNames: "Скрыть имена",
        showNames: "Показать имена",
        progress: "Прогресс",
        directions: "Направления класса",
        confidence: "Уверенность в выборе",
        before: "до",
        after: "после",
        notFit: "{{n}} раз ученик понял, что профессия ему не подходит",
        all: "Все",
        noQuiz: "Не прошли тест",
        noTrial: "Не пробовали профессию",
        student: "Ученик",
        quiz: "Тест",
        direction: "Направление",
        careersTried: "Профессии",
        lastActive: "Последний раз",
        noStudents: "Пока никто не присоединился. Дайте ученикам ссылку или QR.",
        empty: "В этом фильтре никого нет.",
        topCareers: "Подходящие специальности по тесту",
        tried: "Попробованные профессии",
        solved: "решено: {{n}}/{{t}}",
        liked: "понравилось: {{n}}/{{t}}",
        fit: "Подходит",
        notFitShort: "Не подходит",
        plan: "План подачи: выбрано {{n}}",
        remove: "Удалить из класса",
        removeConfirm: "Удалить {{name}} из класса? Результаты не удалятся.",
        archive: "В архив",
        unarchive: "Из архива",
        guest: "без почты",
        notFoundClass: "Класс не найден.",
        error: "Не получилось. Попробуйте ещё раз.",
        demoNote: "Имена скрыты — для показа на экране.",
    },
    en: {
        joinTitle: "Join your class",
        codeLabel: "Class code",
        codePlaceholder: "For example: K7M2QX",
        codeFind: "Find",
        notFound: "No class with this code. Ask your teacher again.",
        full: "The class is full (60 students). Tell your teacher.",
        teacher: "Teacher",
        students: "{{n}} students joined",
        nameLabel: "Your first and last name",
        namePlaceholder: "For example: Jamshed Rahimov",
        nameHint: "No email or password needed — your teacher will know you by this name.",
        asUser: "You are joining as {{name}}.",
        consent: "Your teacher will see your test result and the careers you try. Nobody else will.",
        join: "Join",
        joined: "You are in class “{{name}}”!",
        joinedHint: "Now take the test and try 1–2 careers — your results go to the teacher automatically.",
        startQuiz: "Start the test",
        tryCareer: "Try yourself in a career",
        sameDevice: "Take the test and tries on this same phone or computer — without an email the site only knows you on this device.",
        leave: "Leave the class",
        myClasses: "My class",
        teacherRoom: "Teacher room",
        teacherIntro: "Create your class, give students the code and see which direction they got, which careers they tried and how their confidence changed.",
        requestTitle: "Are you a teacher?",
        studentCardText: "If your teacher gave you a class code, join — your test result and the careers you try will be visible to your teacher, who can help you choose.",
        studentCardButton: "Enter the code",
        teacherCardText: "With the teacher role you see how your students are choosing a career: which direction they got, which careers they tried and how their confidence changed.",
        teacherCardButton: "Get the teacher role",
        requestText: "Send a request — the Teacher room opens after approval.",
        school: "School",
        schoolPlaceholder: "For example: School No. 5, Khujand",
        subject: "Subject (optional)",
        city: "City or district",
        phone: "Phone (optional)",
        send: "Send",
        pending: "Your request was sent and is waiting for approval. Usually within 1 day.",
        rejected: "The request was not approved. If this is a mistake, add details and send again.",
        newClass: "Create a class",
        className: "Class name",
        classNamePlaceholder: "For example: 11 “A”",
        grade: "Grade",
        gradeLabel: "grade {{n}}",
        create: "Create",
        noClasses: "No classes yet. Create the first one — it takes a minute.",
        joinedCount: "joined",
        quizCount: "took the test",
        trialCount: "tried a career",
        archived: "Archived",
        open: "Open",
        back: "All classes",
        share: "Send to students",
        link: "Link",
        copy: "Copy",
        copied: "Copied",
        qr: "QR code for the board or projector",
        telegram: "Text for Telegram",
        telegramText: "Hello! To choose a career, take the “Ikhtisosi man” test and try 1–2 careers (10–15 minutes): {{link}} — class code: {{code}}",
        sendTelegram: "To Telegram",
        reminderText: "Hello! You have not taken the test and career try yet. Please do it by the end of the week: {{link}}",
        copyReminder: "Reminder text",
        refresh: "Refresh",
        csv: "Excel (CSV)",
        print: "Print / PDF",
        hideNames: "Hide names",
        showNames: "Show names",
        progress: "Progress",
        directions: "Class directions",
        confidence: "Confidence in the choice",
        before: "before",
        after: "after",
        notFit: "{{n}} times a student learned a career does not suit them",
        all: "All",
        noQuiz: "No test yet",
        noTrial: "No career tried",
        student: "Student",
        quiz: "Test",
        direction: "Direction",
        careersTried: "Careers",
        lastActive: "Last active",
        noStudents: "Nobody has joined yet. Give students the link or QR.",
        empty: "Nobody in this filter.",
        topCareers: "Matching specialties from the test",
        tried: "Careers tried",
        solved: "solved: {{n}}/{{t}}",
        liked: "liked: {{n}}/{{t}}",
        fit: "Suits",
        notFitShort: "Does not suit",
        plan: "Application plan: {{n}} chosen",
        remove: "Remove from class",
        removeConfirm: "Remove {{name}} from the class? Their results stay.",
        archive: "Archive",
        unarchive: "Unarchive",
        guest: "no email",
        notFoundClass: "Class not found.",
        error: "Something went wrong. Try again.",
        demoNote: "Names hidden — for showing on screen.",
    },
};

export const classText = (language) => CLASS_TEXT[String(language || "tj").slice(0, 2)] || CLASS_TEXT.tj;
export const fill = (text, values) => String(text).replace(/\{\{(\w+)\}\}/g, (_, key) => values?.[key] ?? "");
export const classLink = (code) => `${window.location.origin}/class/${code}`;
// «Ҷамшед Раҳимов» → «Ҷ. Р.» (реҷаи намоиш дар экран).
export const initials = (name) => String(name || "").split(/\s+/).filter(Boolean).map((part) => `${part[0]}.`).join(" ") || "—";
