// «Як рӯз дар ихтисос»: матни интерфейс (матни худи сенарияҳо аз сервер меояд).

// Самти ММТ → сенарияи пешфарз (барои натиҷаи тест).
export const CLUSTER_FAMILY = { 1: "it", 2: "economics", 3: "teacher", 4: "law", 5: "medicine" };
// Ҳамон қоидаи сервер (Back/nest-backend/src/trial/families.ts) барои 5 оилаи тайёр:
// гурӯҳ = рақамҳои 2–3-и рамз; агар мувофиқ наояд — сенарияи пешфарзи кластери ММТ.
// Дар корт ҳисоб мешавад, то барои ҳар корт дархости алоҳида нафиристем.
const READY_FAMILIES = [
    { id: "it", groups: ["40", "53", "55", "98", "B0", "45"], clusters: [1, 2] },
    { id: "economics", groups: ["25", "27", "20", "96"], clusters: [1, 2] },
    { id: "teacher", groups: ["01", "02", "08", "00", "88"], clusters: [1, 2, 3, 4, 5] },
    { id: "law", groups: ["24", "93"], clusters: [4] },
    { id: "medicine", groups: ["79", "80"], clusters: [5] },
];
export function familyForCareer(career) {
    const group = String(career?.code || "").slice(1, 3);
    const cluster = Number(career?.mmtCluster ?? career?.cluster?.clusterNumber) || null;
    const own = READY_FAMILIES.find((family) => family.groups.includes(group) && (!cluster || family.clusters.includes(cluster)));
    return own?.id || (cluster ? CLUSTER_FAMILY[cluster] || null : null);
}

export const FAMILY_ROLE = {
    it: { tj: "Барномасоз", ru: "Программист", en: "Programmer" },
    economics: { tj: "Иқтисодчии мағоза", ru: "Экономист магазина", en: "Shop economist" },
    teacher: { tj: "Омӯзгор", ru: "Учитель", en: "Teacher" },
    law: { tj: "Ҳуқуқшинос", ru: "Юрист", en: "Lawyer" },
    medicine: { tj: "Ҳамшира / табиб", ru: "Медсестра / врач", en: "Nurse / doctor" },
};

export const TRIAL_TEXT = {
    tj: {
        name: "Худро дар касб санҷед",
        tagline: "Касбро на хонед — худатон кунед",
        hubIntro: "«Кори дӯстдошта» ёфта намешавад — он бо санҷидан пайдо мешавад. Ҳар ихтисос сенарияи худро дорад: як рӯзи корӣ, 2 вазифаи касбӣ ва 2 вазифа бо одамон, ҷиҳатҳои мусбат ва манфӣ. Баъд мебинед, ки кадом қисми кор ба шумо писанд аст ва онро дар куҷо омӯхтан мумкин аст.",
        why: [
            ["Бе бақайдгирӣ", "Ҳар кас метавонад санҷад — тақрибан 10 дақиқа."],
            ["Бе дониши махсус", "Ҳамаи маълумоти лозимӣ дар худи вазифа ҳаст."],
            ["Ҳар ҷавоб шарҳ дорад", "Мутахассиси воқеӣ чӣ мекард ва чаро."],
        ],
        searchTitle: "Ихтисоси худро ёбед",
        searchHint: "Ҳар яке аз 884 ихтисос сенарияи худро дорад: рӯзи корӣ, 4 вазифа, ҷиҳатҳои мусбат ва манфӣ.",
        searchPlaceholder: "Масалан: Геодезия, Забони англисӣ, Педиатрия…",
        noResults: "Ихтисос ёфт нашуд. Номи дигарро нависед.",
        samplesTitle: "Намунаҳо (навиштаи муаллиф)",
        start: "Оғоз",
        minutes: "≈ {{n}} дақиқа",
        tasksCount: "3 вазифа",
        soon: "Ба зудӣ",
        soonHint: "Сенарияҳо барои ин гурӯҳҳо навишта мешаванд:",
        family: "Гурӯҳ",
        forCareer: "Барои ихтисоси",
        confBefore: "Пеш аз оғоз: шумо чӣ қадар боварӣ доред, ки ин соҳа барои шумост?",
        confAfter: "Ва ҳоло: чӣ қадар боварӣ доред, ки ин соҳа барои шумост?",
        confScale: ["Тамоман не", "Кам", "Намедонам", "Асосан ҳа", "Комилан"],
        task: "Вазифаи {{n}} аз {{total}}",
        hard: "Малакаи касбӣ",
        soft: "Кор бо одамон",
        check: "Санҷидан",
        pickN: "{{n}} вариантро интихоб кунед",
        orderHint: "Вариантҳоро бо тартиб пахш кунед: аввал — муҳимтарин. Барои бекор кардан боз пахш кунед.",
        yourNumber: "Ҷавоби шумо",
        right: "Дуруст!",
        rightOrder: "Дуруст — муҳимтарин аввал аст.",
        perfectOrder: "Тартиби пурра ҳам дуруст!",
        wrong: "Нодуруст — аммо ин ҳам таҷриба аст.",
        correctOrder: "Тартиби дуруст:",
        correctNumber: "Ҷавоби дуруст: {{n}}",
        whyTitle: "Чаро чунин аст",
        quickInfo: "{{n}} вазифа · ≈ {{m}} дақиқа",
        fitGood: "Ба шумо мувофиқ аст",
        fitOther: "Шояд касби дигар беҳтар бошад",
        tryOtherHint: "Боз як ихтисосро санҷед ва муқоиса кунед — ҳамагӣ 10 дақиқа.",
        hardCount: "{{n}} вазифаи касбӣ",
        softCount: "{{n}} вазифа бо одамон",
        aiNote: "Ин сенарияро AI аз рӯи маълумоти расмии ихтисос (ММТ) сохтааст; мутахассис ҳанӯз насанҷидааст.",
        dayTitle: "Як рӯзи корӣ — аз субҳ то шом",
        tipTitle: "Аз ҳозир машқ кунед:",
        prosTitle: "Ҷиҳатҳои мусбат",
        consTitle: "Ҷиҳатҳои манфӣ",
        goodForTitle: "Ба кӣ мувофиқ аст",
        hardForTitle: "Ба кӣ душвор аст",
        likedOf: "писанд омад: {{n}} аз {{total}}",
        leanHard: "Ба шумо бештар худи кори касбӣ писанд омад, на муошират — ихтисосҳое, ки бештар бо асбоб, ҳуҷҷат ё рақам кор мекунанд, мувофиқтаранд.",
        leanSoft: "Ба шумо бештар кор бо одамон писанд омад — дар ҳамин соҳа вазифаҳое, ки бо мизоҷ, хонанда ё даста кор мекунанд, мувофиқтаранд.",
        leanBoth: "Ба шумо ҳам кори касбӣ ва ҳам кор бо одамон тақрибан баробар писанд омад.",
        careerTitle: "Ихтисоси шумо",
        clusterLabel: "Кластер",
        codeLabel: "Рамз",
        years: "сол",
        save: "Захира кардан",
        saved: "Захира шуд",
        saveLogin: "Барои захира ворид шавед",
        savedOk: "Ихтисос захира шуд — онро дар «Захирашудаҳо» меёбед.",
        unsavedOk: "Аз захира бароварда шуд.",
        fullPage: "Саҳифаи пурраи ихтисос",
        whereTitle: "Дар куҷо таҳсил кардан мумкин",
        whereHint: "Муассиса, шаҳр, шакл, забон ва нарх дар як сол. Барои ҳуҷҷатсупорӣ ба нақша илова кунед.",
        seats: "{{n}} ҷой",
        perYear: "дар як сол",
        addPlan: "Ба нақшаи ҳуҷҷатсупорӣ",
        inPlan: "Дар нақша",
        addPlanLogin: "Барои илова ба нақша ворид шавед",
        planOk: "Ба нақшаи ҳуҷҷатсупорӣ илова шуд.",
        openPlan: "Нақшаи ҳуҷҷатсупориро кушоед",
        noOfferings: "Маълумот дар бораи муассисаҳо барои ин ихтисос ҳанӯз нест.",
        actionError: "Нашуд. Баъдтар кӯшиш кунед.",
        suggestOtherCareer: "Ба назар мерасад, ки ин ихтисос ба шумо он қадар наздик нест — ин ҳам натиҷаи муҳим аст. Ихтисоси дигарро санҷед.",
        tryOtherCareers: "Касби дигарро санҷед",
        realLifeTitle: "Дар кори воқеӣ:",
        skillUsed: "Малакае, ки шумо санҷидед:",
        praise: [
            ["Офарин!", "Шумо мисли мутахассиси воқеӣ фикр кардед."],
            ["Аъло!", "Маҳз ҳамин тавр мутахассис қарор мекунад."],
            ["Баракалло!", "Ин ҷавоби касбӣ буд."],
        ],
        encourage: [
            ["Ҳеҷ гап не — ҳамин тавр меомӯзанд!", "Ҳар мутахассис аввал ҳамин хатоҳоро кардааст. Бинед, ки ҷавоб чӣ гуна аст:"],
            ["Қариб!", "Фикри шумо мантиқ дошт. Ана роҳи мутахассис:"],
            ["Ин ҳам таҷриба аст.", "Акнун медонед, ки дар кори воқеӣ чӣ тавр мекунанд:"],
        ],
        liked: "Ин қисми кор ба шумо шавқовар буд?",
        likeYes: "Ҳа, шавқовар",
        likeNo: "Не, шавқовар нест",
        realityTitle: "Ҳақиқати касб — он чи дар реклама намегӯянд",
        ratingQ: "Ин кор дар маҷмӯъ ба шумо чӣ қадар писанд омад?",
        rating: ["Тамоман не", "Каме", "Хуб", "Хеле!"],
        seeResult: "Хулосаро бинед",
        resultTitle: "Хулосаи шумо",
        solved: "Шумо {{n}} аз {{total}} вазифаро ҳал кардед",
        confChange: "Боварии шумо: {{a}} → {{b}}",
        confUp: "Санҷиш боварии шуморо зиёд кард.",
        confDown: "Санҷиш ба шумо нишон дод, ки шояд ин самт он қадар наздик нест — ин ҳам натиҷаи муҳим аст: 4 соли таҳсил ва пулро сарфа мекунад.",
        confSame: "Боварии шумо ҳамон монд.",
        verdict: {
            strong: "Ҳам ҳал кардед, ҳам шавқовар буд — нишонаи хуб.",
            interest: "Душвор буд, аммо шавқовар. Шавқ бо омӯхтан меафзояд — маҳорат омӯхта мешавад.",
            ability: "Шумо аз уҳдаи он мебароед, аммо шавқ надоред. Шояд ихтисоси ҳамсоя беҳтар бошад.",
            other: "Ин қисм ба шумо наздик нест — ва ин ҳам натиҷаи муҳим аст.",
        },
        relatedTitle: "Ихтисосҳое, ки ба ин қисм наздиканд:",
        suggestOther: "Ба назар мерасад, ки ин соҳа ба шумо наздик нест. Самти дигарро санҷед:",
        others: "Сенарияҳои дигар",
        again: "Аз нав",
        backToCareer: "Ба саҳифаи ихтисос",
        allScenarios: "Ҳамаи сенарияҳо",
        loadError: "Сенария бор нашуд. Интернетро санҷед ва саҳифаро нав кунед.",
        retry: "Аз нав кӯшиш кунед",
        ctaTitle: "Худро дар касб санҷед",
        ctaText: "Пеш аз интихоб худатон санҷед: як рӯзи корӣ, 4 вазифаи воқеии ҳамин ихтисос, ҷиҳатҳои мусбат ва манфӣ.",
        ctaNearest: "Сенария барои гурӯҳи «{{own}}» ҳанӯз навишта мешавад — ҳоло наздиктарин аз ҳамин самт.",
        ctaButton: "Санҷидан",
        quizTitle: "Пеш аз интихоб — санҷед",
        quizMore: "Ё инҳоро санҷед:",
        quizText: "Тест нишон дод, ки ба шумо чӣ писанд аст. Акнун кори воқеии ихтисосро худатон кунед: «{{role}}» — рӯзи корӣ, вазифаҳо, ҷиҳатҳои мусбат ва манфӣ.",
        simplified: "Сенария содда карда шудааст — кори воқеӣ мураккабтар аст. Ҳадаф — шинос шудан, на имтиҳон.",
    },
    ru: {
        name: "Попробуйте себя в профессии",
        tagline: "Не читайте о профессии — попробуйте её",
        hubIntro: "«Любимую работу» не находят — её узнают, попробовав. У каждой специальности свой сценарий: рабочий день, 2 профессиональные задачи и 2 с людьми, плюсы и минусы. Потом вы увидите, какая часть работы вам нравится и где этому учат.",
        why: [
            ["Без регистрации", "Попробовать может каждый — около 10 минут."],
            ["Без специальных знаний", "Всё нужное есть в самой задаче."],
            ["У каждого ответа есть разбор", "Что сделал бы настоящий специалист и почему."],
        ],
        searchTitle: "Найдите свою специальность",
        searchHint: "У каждой из 884 специальностей свой сценарий: рабочий день, 4 задачи, плюсы и минусы.",
        searchPlaceholder: "Например: Геодезия, Английский язык, Педиатрия…",
        noResults: "Специальность не найдена. Попробуйте другое название.",
        samplesTitle: "Примеры (написаны автором)",
        start: "Начать",
        minutes: "≈ {{n}} мин",
        tasksCount: "3 задачи",
        soon: "Скоро",
        soonHint: "Сценарии для этих групп пишутся:",
        family: "Группа",
        forCareer: "Для специальности",
        confBefore: "Перед началом: насколько вы уверены, что эта сфера для вас?",
        confAfter: "А теперь: насколько вы уверены, что эта сфера для вас?",
        confScale: ["Совсем нет", "Слабо", "Не знаю", "Скорее да", "Полностью"],
        task: "Задача {{n}} из {{total}}",
        hard: "Профессиональный навык",
        soft: "Работа с людьми",
        check: "Проверить",
        pickN: "Выберите {{n}} варианта",
        orderHint: "Нажимайте варианты по порядку: первым — самое важное. Нажмите ещё раз, чтобы отменить.",
        yourNumber: "Ваш ответ",
        right: "Верно!",
        rightOrder: "Верно — самое важное стоит первым.",
        perfectOrder: "И весь порядок тоже верный!",
        wrong: "Неверно — но это тоже опыт.",
        correctOrder: "Правильный порядок:",
        correctNumber: "Правильный ответ: {{n}}",
        whyTitle: "Почему так",
        quickInfo: "{{n}} задачи · ≈ {{m}} мин",
        fitGood: "Вам подходит",
        fitOther: "Возможно, лучше другая профессия",
        tryOtherHint: "Попробуйте ещё одну специальность и сравните — всего 10 минут.",
        hardCount: { one: "{{n}} профессиональная задача", few: "{{n}} профессиональные задачи", many: "{{n}} профессиональных задач", other: "{{n}} профессиональной задачи" },
        softCount: { one: "{{n}} задача с людьми", few: "{{n}} задачи с людьми", many: "{{n}} задач с людьми", other: "{{n}} задачи с людьми" },
        aiNote: "Этот сценарий составлен AI по официальным данным специальности (НЦТ); специалист его ещё не проверял.",
        dayTitle: "Рабочий день — с утра до вечера",
        tipTitle: "Тренируйтесь уже сейчас:",
        prosTitle: "Плюсы",
        consTitle: "Минусы",
        goodForTitle: "Кому подходит",
        hardForTitle: "Кому будет трудно",
        likedOf: "понравилось: {{n}} из {{total}}",
        leanHard: "Вам больше понравилась сама профессиональная работа, чем общение — подойдут направления, где больше работы с инструментами, документами или цифрами.",
        leanSoft: "Вам больше понравилась работа с людьми — в этой сфере подойдут роли, где много общения с клиентами, учениками или командой.",
        leanBoth: "Вам примерно одинаково понравились и профессиональные задачи, и работа с людьми.",
        careerTitle: "Ваша специальность",
        clusterLabel: "Кластер",
        codeLabel: "Код",
        years: { one: "год", few: "года", many: "лет", other: "года" },
        save: "Сохранить",
        saved: "Сохранено",
        saveLogin: "Войдите, чтобы сохранить",
        savedOk: "Специальность сохранена — она в разделе «Сохранённые».",
        unsavedOk: "Удалено из сохранённых.",
        fullPage: "Полная страница специальности",
        whereTitle: "Где можно учиться",
        whereHint: "Учебное заведение, город, форма, язык и цена за год. Для подачи документов добавьте в план.",
        seats: { one: "{{n}} место", few: "{{n}} места", many: "{{n}} мест", other: "{{n}} места" },
        perYear: "в год",
        addPlan: "В план подачи документов",
        inPlan: "В плане",
        addPlanLogin: "Войдите, чтобы добавить в план",
        planOk: "Добавлено в план подачи документов.",
        openPlan: "Открыть план подачи документов",
        noOfferings: "Данных об учебных заведениях для этой специальности пока нет.",
        actionError: "Не получилось. Попробуйте позже.",
        suggestOtherCareer: "Похоже, эта специальность вам не очень близка — это тоже важный результат. Попробуйте другую.",
        tryOtherCareers: "Попробовать другую профессию",
        realLifeTitle: "В реальной работе:",
        skillUsed: "Навык, который вы попробовали:",
        praise: [
            ["Отлично!", "Вы рассуждали как настоящий специалист."],
            ["Превосходно!", "Именно так принимает решение специалист."],
            ["Браво!", "Это был профессиональный ответ."],
        ],
        encourage: [
            ["Ничего страшного — так и учатся!", "Каждый специалист когда-то ошибался так же. Вот как правильно:"],
            ["Почти!", "В вашей мысли была логика. Вот путь специалиста:"],
            ["Это тоже опыт.", "Теперь вы знаете, как делают в настоящей работе:"],
        ],
        liked: "Эта часть работы вам была интересна?",
        likeYes: "Да, интересно",
        likeNo: "Нет, неинтересно",
        realityTitle: "Правда о профессии — то, о чём не говорят в рекламе",
        ratingQ: "Насколько вам в целом понравилась эта работа?",
        rating: ["Совсем нет", "Немного", "Хорошо", "Очень!"],
        seeResult: "Посмотреть итог",
        resultTitle: "Ваш итог",
        solved: "Вы решили {{n}} из {{total}} задач",
        confChange: "Ваша уверенность: {{a}} → {{b}}",
        confUp: "Проба повысила вашу уверенность.",
        confDown: "Проба показала, что, возможно, это направление вам не так близко — это тоже важный результат: он экономит 4 года учёбы и деньги.",
        confSame: "Ваша уверенность не изменилась.",
        verdict: {
            strong: "И решили, и было интересно — хороший знак.",
            interest: "Было трудно, но интересно. Интерес растёт с обучением — навык можно освоить.",
            ability: "Вы справляетесь, но интереса нет. Возможно, лучше подойдёт соседняя специальность.",
            other: "Эта часть вам не близка — и это тоже важный результат.",
        },
        relatedTitle: "Специальности, близкие к этой части:",
        suggestOther: "Похоже, эта сфера вам не очень близка. Попробуйте другое направление:",
        others: "Другие сценарии",
        again: "Заново",
        backToCareer: "К специальности",
        allScenarios: "Все сценарии",
        loadError: "Сценарий не загрузился. Проверьте интернет и обновите страницу.",
        retry: "Повторить",
        ctaTitle: "Попробуйте себя в профессии",
        ctaText: "Попробуйте до выбора: рабочий день, 4 настоящие задачи этой специальности, плюсы и минусы.",
        ctaNearest: "Сценарий для группы «{{own}}» ещё пишется — пока ближайший из этого направления.",
        ctaButton: "Попробовать",
        quizTitle: "Прежде чем выбирать — попробуйте",
        quizMore: "Или попробуйте:",
        quizText: "Тест показал, что вам нравится. Теперь сами выполните настоящую работу специальности «{{role}}»: рабочий день, задачи, плюсы и минусы.",
        simplified: "Сценарий упрощён — настоящая работа сложнее. Цель — познакомиться, а не сдать экзамен.",
    },
    en: {
        name: "Try yourself in a career",
        tagline: "Don't read about a job — try it",
        hubIntro: "A \"dream job\" is not found — you discover it by trying. Every specialty has its own scenario: a working day, 2 professional tasks and 2 with people, pros and cons. Then you see which part of the work you enjoy and where it is taught.",
        why: [
            ["No sign-up", "Anyone can try — about 10 minutes."],
            ["No special knowledge", "Everything you need is in the task."],
            ["Every answer is explained", "What a real professional would do and why."],
        ],
        searchTitle: "Find your specialty",
        searchHint: "Each of the 884 specialties has its own scenario: a working day, 4 tasks, pros and cons.",
        searchPlaceholder: "For example: Geodesy, English, Paediatrics…",
        noResults: "No specialty found. Try another name.",
        samplesTitle: "Samples (written by the author)",
        start: "Start",
        minutes: "≈ {{n}} min",
        tasksCount: "3 tasks",
        soon: "Coming soon",
        soonHint: "Scenarios for these groups are being written:",
        family: "Group",
        forCareer: "For the specialty",
        confBefore: "Before you start: how sure are you that this field is for you?",
        confAfter: "And now: how sure are you that this field is for you?",
        confScale: ["Not at all", "A little", "Not sure", "Mostly yes", "Completely"],
        task: "Task {{n}} of {{total}}",
        hard: "Professional skill",
        soft: "Working with people",
        check: "Check",
        pickN: "Choose {{n}} options",
        orderHint: "Tap the options in order: most important first. Tap again to undo.",
        yourNumber: "Your answer",
        right: "Correct!",
        rightOrder: "Correct — the most important comes first.",
        perfectOrder: "And the whole order is right too!",
        wrong: "Not quite — but that is experience too.",
        correctOrder: "The correct order:",
        correctNumber: "The correct answer: {{n}}",
        whyTitle: "Why it works this way",
        quickInfo: "{{n}} tasks · ≈ {{m}} min",
        fitGood: "This suits you",
        fitOther: "Another career may suit you better",
        tryOtherHint: "Try one more specialty and compare — just 10 minutes.",
        hardCount: { one: "{{n}} professional task", other: "{{n}} professional tasks" },
        softCount: { one: "{{n}} task with people", other: "{{n}} tasks with people" },
        aiNote: "This scenario was written by AI from the specialty's official data (NTC); a specialist has not reviewed it yet.",
        dayTitle: "A working day — morning to evening",
        tipTitle: "Practise it now:",
        prosTitle: "Pros",
        consTitle: "Cons",
        goodForTitle: "Who it suits",
        hardForTitle: "Who may find it hard",
        likedOf: "liked: {{n}} of {{total}}",
        leanHard: "You enjoyed the professional work more than talking to people — directions with more tools, documents or numbers may suit you.",
        leanSoft: "You enjoyed working with people more — roles in this field with lots of contact with clients, students or a team may suit you.",
        leanBoth: "You enjoyed the professional tasks and working with people about equally.",
        careerTitle: "Your specialty",
        clusterLabel: "Cluster",
        codeLabel: "Code",
        years: { one: "year", other: "years" },
        save: "Save",
        saved: "Saved",
        saveLogin: "Sign in to save",
        savedOk: "Specialty saved — find it under “Saved”.",
        unsavedOk: "Removed from saved.",
        fullPage: "Full specialty page",
        whereTitle: "Where you can study",
        whereHint: "Institution, city, form, language and price per year. Add to your plan to apply.",
        seats: { one: "{{n}} place", other: "{{n}} places" },
        perYear: "per year",
        addPlan: "Add to application plan",
        inPlan: "In plan",
        addPlanLogin: "Sign in to add to your plan",
        planOk: "Added to your application plan.",
        openPlan: "Open the application plan",
        noOfferings: "No data on institutions for this specialty yet.",
        actionError: "Something went wrong. Please try again later.",
        suggestOtherCareer: "This specialty does not seem very close to you — that is an important result too. Try another one.",
        tryOtherCareers: "Try another career",
        realLifeTitle: "In real work:",
        skillUsed: "The skill you just tried:",
        praise: [
            ["Well done!", "You thought like a real professional."],
            ["Excellent!", "That is exactly how a professional decides."],
            ["Great job!", "That was a professional answer."],
        ],
        encourage: [
            ["No problem — that is how people learn!", "Every professional once made this same mistake. Here is the answer:"],
            ["Almost!", "Your thinking had logic. Here is the professional's way:"],
            ["That is experience too.", "Now you know how it is done in real work:"],
        ],
        liked: "Did you find this part of the work interesting?",
        likeYes: "Yes, interesting",
        likeNo: "No, not really",
        realityTitle: "The truth about the job — what ads don't tell you",
        ratingQ: "Overall, how much did you like this work?",
        rating: ["Not at all", "A little", "Good", "A lot!"],
        seeResult: "See the result",
        resultTitle: "Your result",
        solved: "You solved {{n}} of {{total}} tasks",
        confChange: "Your confidence: {{a}} → {{b}}",
        confUp: "The trial raised your confidence.",
        confDown: "The trial showed this direction may not be that close to you — that is an important result too: it saves 4 years of study and money.",
        confSame: "Your confidence stayed the same.",
        verdict: {
            strong: "You solved it and enjoyed it — a good sign.",
            interest: "Hard, but interesting. Interest grows with learning — the skill can be learned.",
            ability: "You can do it but are not interested. A neighbouring specialty may suit you better.",
            other: "This part does not seem to suit you — and that is an important result too.",
        },
        relatedTitle: "Specialties close to this part:",
        suggestOther: "This field does not seem close to you. Try another direction:",
        others: "Other scenarios",
        again: "Start over",
        backToCareer: "Back to the specialty",
        allScenarios: "All scenarios",
        loadError: "The scenario did not load. Check your connection and refresh.",
        retry: "Try again",
        ctaTitle: "Try yourself in a career",
        ctaText: "Try it before choosing: a working day, 4 real tasks of this specialty, pros and cons.",
        ctaNearest: "The scenario for \"{{own}}\" is still being written — this is the closest one in the same direction.",
        ctaButton: "Try it",
        quizTitle: "Before you choose — try it",
        quizMore: "Or try:",
        quizText: "The test showed what you like. Now do the real work of \"{{role}}\" yourself: a working day, tasks, pros and cons.",
        simplified: "The scenario is simplified — real work is more complex. The goal is to get a feel, not to pass an exam.",
    },
};

export const trialText = (lang) => TRIAL_TEXT[String(lang || "tj").slice(0, 2)] || TRIAL_TEXT.tj;
export const fillText = (text, values) => String(text).replace(/\{\{(\w+)\}\}/g, (_, key) => values[key] ?? "");
// Шакли дурусти ҷамъ: «1 место / 2 места / 5 мест», «1 place / 2 places». Тоҷикӣ — як шакл (сатр).
export const plural = (forms, n, lang) => {
    if (typeof forms === "string") return fillText(forms, { n });
    const rule = new Intl.PluralRules(lang === "ru" ? "ru" : "en").select(Number(n) || 0);
    return fillText(forms[rule] ?? forms.other ?? forms.many, { n });
};
export const langCode = (lang) => {
    const code = String(lang || "tj").slice(0, 2);
    return code === "ru" || code === "en" ? code : "tj";
};
