// «Як рӯз дар ихтисос»: матни интерфейс (матни худи сенарияҳо аз сервер меояд).

// Самти ММТ → сенарияи пешфарз (барои натиҷаи тест).
export const CLUSTER_FAMILY = { 1: "it", 2: "economics", 3: "teacher", 4: "law", 5: "medicine" };
// Ҳамон қоидаи сервер (Back/nest-backend/src/trial/families.ts) барои 5 оилаи тайёр:
// гурӯҳ = рақамҳои 2–3-и рамз; агар мувофиқ наояд — сенарияи пешфарзи кластери ММТ.
// Дар корт ҳисоб мешавад, то барои ҳар корт дархости алоҳида нафиристем.
const READY_FAMILIES = [
    { id: "it", groups: ["40", "53", "55", "98", "B0", "45"], clusters: [1, 2] },
    { id: "economics", groups: ["25", "27", "20", "96"], clusters: [1, 2] },
    { id: "teacher", groups: ["01", "02", "08", "00", "88"], clusters: [1, 2, 3, 4, 5] },
    { id: "law", groups: ["24", "93"], clusters: [4] },
    { id: "medicine", groups: ["79", "80"], clusters: [5] },
];
export function familyForCareer(career) {
    const group = String(career?.code || "").slice(1, 3);
    const cluster = Number(career?.mmtCluster ?? career?.cluster?.clusterNumber) || null;
    const own = READY_FAMILIES.find((family) => family.groups.includes(group) && (!cluster || family.clusters.includes(cluster)));
    return own?.id || (cluster ? CLUSTER_FAMILY[cluster] || null : null);
}

export const FAMILY_ROLE = {
    it: { tj: "Барномасоз", ru: "Программист", en: "Programmer", icon: "💻" },
    economics: { tj: "Иқтисодчии мағоза", ru: "Экономист магазина", en: "Shop economist", icon: "📊" },
    teacher: { tj: "Омӯзгор", ru: "Учитель", en: "Teacher", icon: "📚" },
    law: { tj: "Ҳуқуқшинос", ru: "Юрист", en: "Lawyer", icon: "⚖️" },
    medicine: { tj: "Ҳамшира / табиб", ru: "Медсестра / врач", en: "Nurse / doctor", icon: "🩺" },
};

export const TRIAL_TEXT = {
    tj: {
        name: "Як рӯз дар ихтисос",
        tagline: "Касбро на хонед — 10 дақиқа худатон кунед",
        hubIntro: "«Кори дӯстдошта» ёфта намешавад — он бо санҷидан пайдо мешавад. Ҳар сенария 3 вазифаи воқеии як рӯзи корӣ аст: 2 вазифаи касбӣ ва 1 вазифа бо одамон. Баъд мебинед, ки кадом қисми кор ба шумо писанд аст.",
        why: [
            ["Бе бақайдгирӣ", "Ҳар кас метавонад санҷад — тақрибан 10 дақиқа."],
            ["Бе дониши махсус", "Ҳама маълумоти лозимӣ дар худи вазифа ҳаст."],
            ["Ҳар ҷавоб шарҳ дорад", "Мутахассиси воқеӣ чӣ мекард ва чаро."],
        ],
        start: "Оғоз",
        minutes: "≈ {{n}} дақиқа",
        soon: "Ба зудӣ",
        soonHint: "Сенарияҳо барои ин гурӯҳҳо навишта мешаванд:",
        family: "Гурӯҳ",
        forCareer: "Барои ихтисоси",
        confBefore: "Пеш аз оғоз: шумо чӣ қадар боварӣ доред, ки ин соҳа барои шумост?",
        confAfter: "Ва ҳоло: чӣ қадар боварӣ доред, ки ин соҳа барои шумост?",
        confScale: ["Тамоман не", "Кам", "Намедонам", "Бештар ҳа", "Комилан"],
        task: "Вазифаи {{n}} аз 3",
        hard: "Малакаи касбӣ",
        soft: "Кор бо одамон",
        check: "Санҷидан",
        pickN: "{{n}} вариантро интихоб кунед",
        orderHint: "Вариантҳоро бо тартиб пахш кунед: аввал — муҳимтарин. Барои бекор кардан боз пахш кунед.",
        yourNumber: "Ҷавоби шумо",
        right: "Дуруст!",
        rightOrder: "Дуруст — муҳимтарин аввал аст.",
        perfectOrder: "Тартиби пурра ҳам дуруст!",
        wrong: "Не дуруст — аммо ин ҳам таҷриба аст.",
        correctOrder: "Тартиби дуруст:",
        correctNumber: "Ҷавоби дуруст: {{n}}",
        whyTitle: "Мутахассис чӣ тавр фикр мекунад",
        liked: "Ин қисми кор ба шумо шавқовар буд?",
        likeYes: "Ҳа, шавқовар",
        likeNo: "Не, шавқовар нест",
        realityTitle: "Ҳақиқати касб — он чи дар реклама намегӯянд",
        ratingQ: "Ин кор дар маҷмӯъ ба шумо чӣ қадар писанд омад?",
        rating: ["Тамоман не", "Каме", "Хуб", "Хеле!"],
        seeResult: "Хулосаро бинед",
        resultTitle: "Хулосаи шумо",
        solved: "Шумо {{n}} аз 3 вазифаро ҳал кардед",
        confChange: "Боварии шумо: {{a}} → {{b}}",
        confUp: "Санҷиш боварии шуморо зиёд кард.",
        confDown: "Санҷиш ба шумо нишон дод, ки шояд ин самт он қадар наздик нест — ин ҳам натиҷаи муҳим аст: 4 сол таҳсил ва пулро наҷот медиҳад.",
        confSame: "Боварии шумо ҳамон монд.",
        verdict: {
            strong: "Ҳам ҳал кардед, ҳам шавқовар буд — нишонаи хуб.",
            interest: "Душвор буд, аммо шавқовар. Шавқ бо омӯхтан меафзояд — маҳорат омӯхта мешавад.",
            ability: "Шумо уҳдабаро мекунед, аммо шавқ надоред. Шояд ихтисоси ҳамсоя беҳтар бошад.",
            other: "Ин қисм ба шумо наздик нест — ва ин ҳам натиҷаи муҳим аст.",
        },
        relatedTitle: "Ихтисосҳое, ки ба ин қисм наздиканд:",
        suggestOther: "Ба назар мерасад, ки ин соҳа ба шумо наздик нест. Самти дигарро санҷед:",
        others: "Сенарияҳои дигар",
        again: "Аз нав",
        backToCareer: "Ба саҳифаи ихтисос",
        allScenarios: "Ҳамаи сенарияҳо",
        loadError: "Сенария бор нашуд. Интернетро санҷед ва саҳифаро нав кунед.",
        retry: "Аз нав кӯшиш кунед",
        ctaTitle: "Як рӯз дар ихтисос — 10 дақиқа",
        ctaText: "Пеш аз интихоб касбро санҷед: 3 вазифаи воқеии {{role}}.",
        ctaNearest: "Сенария барои гурӯҳи «{{own}}» ҳанӯз навишта мешавад — ҳоло наздиктарин аз ҳамин самт.",
        ctaButton: "Санҷидан",
        quizTitle: "Пеш аз интихоб — санҷед",
        quizText: "Тест нишон дод, ки ба шумо чӣ писанд аст. Акнун 10 дақиқа кори воқеии ин самтро худатон кунед: «{{role}}».",
        simplified: "Сенария содда карда шудааст — кори воқеӣ мураккабтар аст. Ҳадаф — шинос шудан, на имтиҳон.",
    },
    ru: {
        name: "День в профессии",
        tagline: "Не читайте о профессии — попробуйте её 10 минут",
        hubIntro: "«Любимую работу» не находят — её узнают, попробовав. Каждый сценарий — 3 настоящие задачи одного рабочего дня: 2 профессиональные и 1 с людьми. Потом вы увидите, какая часть работы вам нравится.",
        why: [
            ["Без регистрации", "Попробовать может каждый — около 10 минут."],
            ["Без специальных знаний", "Всё нужное есть в самой задаче."],
            ["У каждого ответа есть разбор", "Что сделал бы настоящий специалист и почему."],
        ],
        start: "Начать",
        minutes: "≈ {{n}} мин",
        soon: "Скоро",
        soonHint: "Сценарии для этих групп пишутся:",
        family: "Группа",
        forCareer: "Для специальности",
        confBefore: "Перед началом: насколько вы уверены, что эта сфера для вас?",
        confAfter: "А теперь: насколько вы уверены, что эта сфера для вас?",
        confScale: ["Совсем нет", "Слабо", "Не знаю", "Скорее да", "Полностью"],
        task: "Задача {{n}} из 3",
        hard: "Профессиональный навык",
        soft: "Работа с людьми",
        check: "Проверить",
        pickN: "Выберите {{n}} варианта",
        orderHint: "Нажимайте варианты по порядку: первым — самое важное. Нажмите ещё раз, чтобы отменить.",
        yourNumber: "Ваш ответ",
        right: "Верно!",
        rightOrder: "Верно — самое важное стоит первым.",
        perfectOrder: "И весь порядок тоже верный!",
        wrong: "Неверно — но это тоже опыт.",
        correctOrder: "Правильный порядок:",
        correctNumber: "Правильный ответ: {{n}}",
        whyTitle: "Как думает специалист",
        liked: "Эта часть работы вам была интересна?",
        likeYes: "Да, интересно",
        likeNo: "Нет, неинтересно",
        realityTitle: "Правда о профессии — то, о чём не говорят в рекламе",
        ratingQ: "Насколько вам в целом понравилась эта работа?",
        rating: ["Совсем нет", "Немного", "Хорошо", "Очень!"],
        seeResult: "Посмотреть итог",
        resultTitle: "Ваш итог",
        solved: "Вы решили {{n}} из 3 задач",
        confChange: "Ваша уверенность: {{a}} → {{b}}",
        confUp: "Проба повысила вашу уверенность.",
        confDown: "Проба показала, что, возможно, это направление вам не так близко — это тоже важный результат: он экономит 4 года учёбы и деньги.",
        confSame: "Ваша уверенность не изменилась.",
        verdict: {
            strong: "И решили, и было интересно — хороший знак.",
            interest: "Было трудно, но интересно. Интерес растёт с обучением — навык можно освоить.",
            ability: "Вы справляетесь, но интереса нет. Возможно, лучше подойдёт соседняя специальность.",
            other: "Эта часть вам не близка — и это тоже важный результат.",
        },
        relatedTitle: "Специальности, близкие к этой части:",
        suggestOther: "Похоже, эта сфера вам не очень близка. Попробуйте другое направление:",
        others: "Другие сценарии",
        again: "Заново",
        backToCareer: "К специальности",
        allScenarios: "Все сценарии",
        loadError: "Сценарий не загрузился. Проверьте интернет и обновите страницу.",
        retry: "Повторить",
        ctaTitle: "День в профессии — 10 минут",
        ctaText: "Попробуйте профессию до выбора: 3 настоящие задачи — {{role}}.",
        ctaNearest: "Сценарий для группы «{{own}}» ещё пишется — пока ближайший из этого направления.",
        ctaButton: "Попробовать",
        quizTitle: "Прежде чем выбирать — попробуйте",
        quizText: "Тест показал, что вам нравится. Теперь 10 минут поработайте сами в этом направлении: «{{role}}».",
        simplified: "Сценарий упрощён — настоящая работа сложнее. Цель — познакомиться, а не сдать экзамен.",
    },
    en: {
        name: "A day in the job",
        tagline: "Don't read about a job — try it for 10 minutes",
        hubIntro: "A \"dream job\" is not found — you discover it by trying. Each scenario is 3 real tasks from one working day: 2 professional tasks and 1 with people. Then you see which part of the work you enjoy.",
        why: [
            ["No sign-up", "Anyone can try — about 10 minutes."],
            ["No special knowledge", "Everything you need is in the task."],
            ["Every answer is explained", "What a real professional would do and why."],
        ],
        start: "Start",
        minutes: "≈ {{n}} min",
        soon: "Coming soon",
        soonHint: "Scenarios for these groups are being written:",
        family: "Group",
        forCareer: "For the specialty",
        confBefore: "Before you start: how sure are you that this field is for you?",
        confAfter: "And now: how sure are you that this field is for you?",
        confScale: ["Not at all", "A little", "Not sure", "Mostly yes", "Completely"],
        task: "Task {{n}} of 3",
        hard: "Professional skill",
        soft: "Working with people",
        check: "Check",
        pickN: "Choose {{n}} options",
        orderHint: "Tap the options in order: most important first. Tap again to undo.",
        yourNumber: "Your answer",
        right: "Correct!",
        rightOrder: "Correct — the most important comes first.",
        perfectOrder: "And the whole order is right too!",
        wrong: "Not quite — but that is experience too.",
        correctOrder: "The correct order:",
        correctNumber: "The correct answer: {{n}}",
        whyTitle: "How a professional thinks",
        liked: "Did you find this part of the work interesting?",
        likeYes: "Yes, interesting",
        likeNo: "No, not really",
        realityTitle: "The truth about the job — what ads don't tell you",
        ratingQ: "Overall, how much did you like this work?",
        rating: ["Not at all", "A little", "Good", "A lot!"],
        seeResult: "See the result",
        resultTitle: "Your result",
        solved: "You solved {{n}} of 3 tasks",
        confChange: "Your confidence: {{a}} → {{b}}",
        confUp: "The trial raised your confidence.",
        confDown: "The trial showed this direction may not be that close to you — that is an important result too: it saves 4 years of study and money.",
        confSame: "Your confidence stayed the same.",
        verdict: {
            strong: "You solved it and enjoyed it — a good sign.",
            interest: "Hard, but interesting. Interest grows with learning — the skill can be learned.",
            ability: "You can do it but are not interested. A neighbouring specialty may suit you better.",
            other: "This part is not for you — and that is an important result too.",
        },
        relatedTitle: "Specialties close to this part:",
        suggestOther: "This field does not seem close to you. Try another direction:",
        others: "Other scenarios",
        again: "Start over",
        backToCareer: "Back to the specialty",
        allScenarios: "All scenarios",
        loadError: "The scenario did not load. Check your connection and refresh.",
        retry: "Try again",
        ctaTitle: "A day in the job — 10 minutes",
        ctaText: "Try the job before choosing: 3 real tasks of a {{role}}.",
        ctaNearest: "The scenario for \"{{own}}\" is still being written — this is the closest one in the same direction.",
        ctaButton: "Try it",
        quizTitle: "Before you choose — try it",
        quizText: "The test showed what you like. Now spend 10 minutes doing real work in this direction: \"{{role}}\".",
        simplified: "The scenario is simplified — real work is more complex. The goal is to get a feel, not to pass an exam.",
    },
};

export const trialText = (lang) => TRIAL_TEXT[String(lang || "tj").slice(0, 2)] || TRIAL_TEXT.tj;
export const fillText = (text, values) => String(text).replace(/\{\{(\w+)\}\}/g, (_, key) => values[key] ?? "");
export const langCode = (lang) => {
    const code = String(lang || "tj").slice(0, 2);
    return code === "ru" || code === "en" ? code : "tj";
};
