// English sentences for voice recording (fine-tune from facebook/mms-tts-eng).
// First part — what the assistant actually says. Numbers are written as words.
window.SENTENCE_SETS = window.SENTENCE_SETS || {};
window.SENTENCE_SETS.eng = [
    // ── Assistant: greeting and ready replies ───────────────────────
    "Welcome! I am your assistant.",
    "What shall we do — choose a specialty, look at universities, or take the test?",
    "Here are the specialties.",
    "Opened.",
    "The comparison is ready.",
    "Saved.",
    "Starting the test.",
    "Here are the universities.",
    "I opened your report.",
    "Here is the application plan.",
    "Looking for the nearest universities.",
    "Here is that cluster.",
    "Chat opened.",
    "Here are your saved specialties.",
    "This is the about page.",
    "Going to the home page.",
    "Language changed.",
    "Theme changed.",
    "Sorry, I cannot answer right now. Please say it again.",
    "Sorry, I did not catch that. Please say it once more.",
    "Hello! Shall we choose a specialty, look at universities, or take the test?",
    "You are welcome! How else can I help?",
    "I am the voice assistant of the project My Specialty.",
    "I find specialties, show universities and run the career test.",
    "Would you like to save it or compare it with another one?",
    "Which one do you like more?",

    // ── Assistant: page guides ──────────────────────────────────────
    "All specialties are divided into five clusters.",
    "Natural sciences and engineering, economics, languages and arts, law and society, medicine and sport.",
    "Which one is closer to you? If you are not sure, it is better to take the test once.",
    "This is the home page.",
    "We help you choose the right specialty out of eight hundred eighty four specialties in Tajikistan.",
    "To keep your test results, it is better to sign up.",
    "Here you can see all specialties.",
    "A specialty is the profession you study at university.",
    "Tell me who you want to become, for example a doctor or a programmer, and I will show the directions.",
    "Here are all the universities of Tajikistan on the map.",
    "I can find the university nearest to you or show the universities of one city.",
    "Our goal is to help young people in Tajikistan choose a career using accurate data.",
    "Passing scores, universities and prices come from official sources.",
    "This is the artificial intelligence recommendation.",
    "It tells you which specialties suit you and where to apply.",
    "This is the chat. Ask anything about a specialty, salary or university.",
    "Here you can compare specialties.",
    "This is your application list. I can sort it from nearest to farthest, or free places first.",
    "This is your dashboard: test results, recommendations, chat and comparison.",
    "The test has started. Answer honestly — there are no right or wrong answers.",

    // ── Assistant: specialty brief ──────────────────────────────────
    "With this specialty you can work in hospitals, clinics and laboratories.",
    "You will study programming, databases and computer networks.",
    "The starting salary is from two thousand five hundred to five thousand somoni.",
    "Last year the passing score was from one hundred to three hundred.",
    "Eight universities teach this specialty.",
    "Similar specialties are computer science and cyber security.",
    "To become a doctor, there are these directions: general doctor, pediatrician, dentist, pharmacist and nurse.",
    "The nearest university is two kilometers away from you.",
    "There are free places at three universities in Dushanbe.",

    // ── Study and careers ───────────────────────────────────────────
    "The National Testing Center holds entrance exams every summer.",
    "An applicant can choose up to twelve specialties.",
    "The passing score depends on the number of places and applicants.",
    "Documents are accepted from the first of June to the fifteenth of July.",
    "The Tajik National University has more than twenty faculties.",
    "The medical university is in the center of Dushanbe.",
    "The technical university trains engineers and programmers.",
    "Students live in a dormitory near the main building.",
    "Students with good grades receive a scholarship.",
    "A bachelor's degree takes four years, and a master's degree takes two.",
    "Doctors study for six years and then do their residency.",
    "Lawyers work in courts, prosecutor's offices and private companies.",
    "Economists are needed in banks, tax services and factories.",
    "Math teachers are in high demand in schools.",
    "A programmer writes code and builds mobile apps.",
    "A journalist gathers news and conducts interviews.",
    "A translator knows several languages and helps people understand each other.",
    "An architect designs houses, bridges and whole neighborhoods.",
    "A veterinarian treats pets and farm animals.",
    "A pharmacist knows how medicines work.",
    "A psychologist helps people cope with difficulties.",
    "An agronomist grows cotton, wheat and fruit.",
    "An engineer keeps the power station running.",
    "A designer creates logos, posters and websites.",
    "A coach prepares athletes for competitions.",
    "An accountant keeps track of a company's income and expenses.",

    // ── Cities and nature ───────────────────────────────────────────
    "Dushanbe is the capital of Tajikistan.",
    "Khujand is the second largest city in the country.",
    "Bokhtar, Kulob and Khorog also have their own universities.",
    "Mountains cover more than ninety percent of the country.",
    "The Vakhsh River gives electricity to the whole country.",
    "In spring, apricot and cherry trees bloom in the valleys.",
    "In summer it can be very hot in Dushanbe, up to forty degrees.",
    "The Pamirs are called the roof of the world.",
    "Navruz is the holiday of spring and the new year.",

    // ── General sentences: varied sounds ────────────────────────────
    "The quick brown fox jumps over the lazy dog.",
    "She sells sea shells by the sea shore.",
    "We met by the fountain at exactly six o'clock.",
    "This morning a quiet, warm rain was falling.",
    "Grandmother baked a pie with apples and cinnamon.",
    "The train arrives at platform three in ten minutes.",
    "Please close the window, it is getting cold.",
    "I forgot my phone at home and went back for it.",
    "The cat slept on the windowsill all day long.",
    "The children played in the yard until evening.",
    "My brother is in the eleventh grade.",
    "My sister dreams of becoming a doctor, like our mother.",
    "My father has worked as an engineer for twenty years.",
    "Every morning I exercise and have breakfast.",
    "On Saturday we will go to the mountains with friends.",
    "The shop opens at nine and closes at eight.",
    "He is reading a book about space and the stars.",
    "The teacher explained the problem once again.",
    "The answer was simpler than we thought.",
    "Do not be afraid to make mistakes — that is how we learn.",
    "A good profession brings not only money but also joy.",
    "It is important to choose work that truly interests you.",
    "If you are unsure, talk to your parents and teachers.",
    "Try different activities before you make a decision.",
    "Knowing languages opens many doors.",
    "Computers have become part of our everyday life.",
    "Artificial intelligence helps doctors make a diagnosis.",
    "Internet speed in the city has grown noticeably.",
    "The new bridge joined the two banks of the river.",
    "The plane took off from Dushanbe to Istanbul.",
    "Tourists took photos of the old fortress.",
    "Musicians played the rubob and the doira.",
    "Chess develops logic and patience.",
    "The football match ended with a score of two to one.",
    "The athlete ran ten kilometers in forty minutes.",
    "A new children's ward opened at the hospital.",
    "The nurse measured his blood pressure and temperature.",
    "The doctor prescribed medicine for one week.",
    "Drink more water in hot weather.",
    "Healthy sleep lasts seven or eight hours.",
    "The farmer gathered a rich harvest of grapes.",
    "At the market they sell pomegranates, melons and watermelons.",
    "Prices at the market change every day.",
    "The bank gave a loan to start a business.",
    "The court reviewed the case and made a decision.",
    "Every citizen has the right to education.",
    "The law must be the same for everyone.",
    "A painting exhibition opened at the national museum.",
    "Rudaki is considered the founder of Persian poetry.",
    "Avicenna was a great doctor and scientist.",
    "History teaches us not to repeat mistakes.",
    "Chemistry explains what everything around us is made of.",
    "Physics studies motion, light and energy.",
    "Biology tells us about living things.",
    "Mathematics is the language of all exact sciences.",
    "Although it was late, the lights were still on.",
    "Thank you very much for your help yesterday.",
    "Whether you walk or ride, the view is beautiful.",
    "The judge thought through every piece of evidence.",
    "Measure twice and cut once.",
    "Visit the zoo and watch the giraffes and zebras.",

    // ── Questions and exclamations ──────────────────────────────────
    "What is your name?",
    "How old are you?",
    "Which city do you live in?",
    "Which subjects do you like the most?",
    "Do you want to study for free or pay for your studies?",
    "When does the application period start?",
    "Where is the nearest university?",
    "How much does it cost to study here?",
    "What was the passing score last year?",
    "What do students learn in this specialty?",
    "Is it true that programmers earn a lot?",
    "Great! You are on the right track.",
    "Congratulations, you have finished the test!",
    "Attention! The application deadline is coming soon.",
    "Do not worry, you will succeed.",
    "Wait a moment, I am looking for the information.",
    "Done! Here is what I found.",
    "Unfortunately, nothing was found for this request.",
    "Try to say it another way.",

    // ── Numbers as words ────────────────────────────────────────────
    "One, two, three, four, five, six, seven, eight, nine, ten.",
    "Eleven, twelve, thirteen, fourteen, fifteen, sixteen.",
    "Twenty, thirty, forty, fifty, sixty, seventy, eighty, ninety.",
    "One hundred, two hundred, five hundred, one thousand.",
    "Two thousand twenty five.",
    "Three thousand five hundred somoni per month.",
    "Two hundred ninety five points out of three hundred.",
    "First, second and third place.",
    "September fifteenth, half past seven in the morning.",
];
